using System.Collections.Generic;
using UnityEngine;

public class StockBoxController : MonoBehaviour
{
    public StockInfo info;

    public List<Transform> bigDrinkPoints;
    public List<Transform> cerealPoints, tubeChipsPoints, fruitPoints, largeFruitPoints;

    public List<StockObject> stockInBox;

    public Rigidbody theRB;
    public Collider col;

    public float moveSpeed = 5f;

    public GameObject flap1, flap2;

    public bool testFill;

    private bool isHeld;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (testFill == true)
        {
            testFill = false;

            SetupBox(info);
        }

        if (isHeld == true)
        {
            transform.localPosition = Vector3.MoveTowards(transform.localPosition, Vector3.zero, moveSpeed * Time.deltaTime);
            transform.localRotation = Quaternion.Slerp(transform.localRotation, Quaternion.identity, moveSpeed * Time.deltaTime);
        }
    }

    public void SetupBox(StockInfo stockType)
    {
        info = stockType;

        List<Transform> activePoints = new List<Transform>();

        switch (info.typeOfStock)
        {
            case StockInfo.StockType.bigDrink:
                activePoints = bigDrinkPoints;
                break;
            case StockInfo.StockType.cereal:
                activePoints = cerealPoints;
                break;
            case StockInfo.StockType.chipsTube:
                activePoints = tubeChipsPoints;
                break;
            case StockInfo.StockType.fruit:
                activePoints = fruitPoints;
                break;
            case StockInfo.StockType.fruitLarge:
                activePoints = largeFruitPoints;
                break;
        }

        if (stockInBox.Count == 0)
        {
            for (int i = 0; i < activePoints.Count; i++)
            {
                StockObject stock = Instantiate(stockType.stockObject, activePoints[i]);
                stock.transform.localPosition = Vector3.zero;
                stock.transform.localRotation = Quaternion.identity;

                stockInBox.Add(stock);

                stock.PlaceInBox();
            }
        }
    }

    public void Pickup()
    {
        theRB.isKinematic = true;

        col.enabled = false;

        isHeld = true;

        if (AudioManager.instance != null)
        {
            AudioManager.instance.PlaySFX(1);
        }
    }

    public void Release()
    {
        theRB.isKinematic = false;
        col.enabled = true;

        isHeld = false;

        if (AudioManager.instance != null)
        {
            AudioManager.instance.PlaySFX(0);
        }
    }

    public void OpenClose()
    {
        if (flap1.activeSelf == true)
        {
            flap1.SetActive(false);
            flap2.SetActive(false);
        }
        else
        {
            flap1.SetActive(true);
            flap2.SetActive(true);
        }

        if (AudioManager.instance != null)
        {
            AudioManager.instance.PlaySFX(2);
        }
    }

    public void PlaceStockOnShelf(ShelfSpaceController shelf)
    {
        if (stockInBox.Count > 0)
        {
            shelf.PlaceStock(stockInBox[stockInBox.Count - 1]);

            if (stockInBox[stockInBox.Count - 1].isPlaced == true)
            {
                stockInBox.RemoveAt(stockInBox.Count - 1);
            }
        }

        if (flap1.activeSelf == true)
        {
            OpenClose();
        }
    }

    public int GetStockAmount(StockInfo.StockType stockType)
    {
        int toReturn = 0;

        switch (stockType)
        {
            case StockInfo.StockType.bigDrink:
                toReturn = bigDrinkPoints.Count;
                break;
            case StockInfo.StockType.cereal:
                toReturn = cerealPoints.Count;
                break;
            case StockInfo.StockType.chipsTube:
                toReturn = tubeChipsPoints.Count;
                break;
            case StockInfo.StockType.fruit:
                toReturn = fruitPoints.Count;
                break;
            case StockInfo.StockType.fruitLarge:
                toReturn = largeFruitPoints.Count;
                break;
        }

        return toReturn;
    }
}
